In [1]:
import numpy as np

### Podemos criar um array unidimensional atribuindo-o a uma variável e chamando-o em seguida:

In [2]:

a1 = np.array([1, 2, 3, 4, 5, 6])
a1

array([1, 2, 3, 4, 5, 6])

### Um array bidimensional ficaria assim:

In [3]:

a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Um array n-dimensional poderia ser:

In [4]:

a3 = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],[[0, 1, 2, 3],[4, 5, 6, 7]],[[0 ,1 ,2, 3],[4, 5, 6, 7]]])
a3

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

### Isto gerará um array com os números de 0 a 99.

#### Os métodos np.zeros(), np.ones e np.empy() 
#### funcionam de forma parecida. O primeiro gera um array de zeros.
#### O segundo, de números 1 (um). O terceiro, uma lista com elementos numéricos quaisquer.
#### Entre parênteses, devemos informar a quantidade de elementos do array.

In [6]:

a4 = np.arange(100)
a4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### Podemos ordenar um array com o método sort():

In [9]:

a5 = np.array([6, 7, 2, 4, 5, 3, 8, 1, 9, 0])
np.sort(a5)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Ou remodelar um array — no nosso caso, de 9 elementos para 3 linhas e 3 colunas — com reshape():

In [10]:
a6 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a6.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### concatenar dois arrays em um único com concatenate():

In [11]:
a71 = np.array([0,1,2,3,4])
a72 = np.array([5,6,7,8,9])
np.concatenate((a71, a72))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Podemos fatiar um array em outros arrays, da mesma forma que fazemos fatiamento (slicing) em listas de Python:

In [12]:
a80 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a81 = a80[3:6] # Resultado: array([3, 4, 5])
a82 = a80[5:]  # Resultado: array([5, 6, 7, 8, 9])

In [13]:
a81

array([3, 4, 5])

In [14]:
a82

array([5, 6, 7, 8, 9])

### Podemos, também, dividir uma matriz com duas colunas em dois arrays diferentes com array_split():

In [16]:
a90 = np.array([[1, 2, 3, 4, 5],['a','b','c','d','e']])
a91 = np.array_split(a90, (2))
a91

[array([['1', '2', '3', '4', '5']], dtype='<U11'),
 array([['a', 'b', 'c', 'd', 'e']], dtype='<U11')]

### O método ndim permite saber a dimensão (como, neste exemplo, do nosso array atribuído à variável a3, anteriormente):

In [18]:
a3.ndim
# Resultado: 3 (significa que tem 3 dimensões)

3

### Para o tamanho, usamos size

In [19]:
a3.size
# Resultado: 3 (significa que tem 24 elementos)

24

### Nosso array a1 possui 6 elementos, de 1 a 6. Podemos fatiar todos os que estão antes do índice 3 com:

In [20]:
a1[a1 < 3]
# Resultado: array([1, 2])

array([1, 2])

### encontrar todos os elementos divisíveis por 2 com:


In [21]:
a1[a1%2==0]
# Resultado: array([2, 4, 6])

array([2, 4, 6])

### Operações básicas

In [22]:
b1 = np.array([1,2,2,1])
b2 = np.array([2,2,1,2])
print(b1 + b2)
print(b1 - b2)
print(b1 * b2)
print(b1 / b2)

[3 4 3 3]
[-1  0  1 -1]
[2 4 2 2]
[0.5 1.  2.  0.5]


### Se quisermos somar todos os elementos de arrays, usamos sum():

In [23]:
b3 = np.array([0,1,2,3,4,5,6,7,8,9])
b3.sum()

45

### Precisamos saber qual o maior elemento? Usamos max():

In [24]:
b3.max()

9

### O menor elemento é buscado com min():

In [25]:
b3.min()

0

### Queremos a média, uma medida já da Estatística Descritiva? Numpy fornece por meio de mean():

In [26]:
b3.mean()
# Resultado: 4.5

4.5

### Para multiplicar todos os elementos de um vetor, usamos prod():

In [27]:
b4 = ([1,3,5])
np.prod(b4)
# Resultado: 15

15